import Link from "next/link"
import "../styles/estilos.css";
import Nav from "@/styles/componentes/Nav";
import { Montserrat } from "next/font/google";

const fuente=Montserrat({
  weight:'400',
  subsets:['latin']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Nav/>
        <div className={fuente.className}>{children}</div>
      </body>
    </html>
  )
}
